In [3]:
import dimod

In [4]:
#Global Parameters
Kb = 1.0
JJ = 1.0 #JJ>0 ferromagnetic prefers lowering energy when adjacent spins are identical
mu = 1.0

In [5]:
#Assigning bias and couplers for Ising Model
B= 1.2  
b=-1.0*mu*B  #bias
c=-1.0*JJ  #coupler

In [6]:
#Consider array of 9 spins in 3 by 3 lattice with 0,1,2 in first row , 3,4,5 in second and 6,7,8 in last row.
 
linear={0:b, 1: b, 2: b , 3: b , 4:b , 5:b,6:b ,7:b}
# this is the later part in Hamiltonian due to field B

 
quadratic={(0,1):c, (0,3):c, (0,2):c ,(0,6):c, (1,2):c, (1,4):c, (1,7):c\
          ,(2,5):c, (2,8):c, (3,4):c, (3,6):c, (3,5):c, (4,5):c, (4,7):c\
          ,(5,8):c, (6,7):c, (6,8):c, (7,8):c}
# the possible neighbors interaction result in potential ,and the weights are all equal defined by JJ


In [7]:
#We now check using dimod sampler, minimum energy should be when all flip up i.e All spins (+1) for JJ>0
sampleset = dimod.ExactSolver().sample_ising(linear,quadratic)
print(sampleset)

     0  1  2  3  4  5  6  7  8 energy num_oc.
341 +1 +1 +1 +1 +1 +1 +1 +1 +1  -27.6       1
170 +1 +1 +1 +1 +1 +1 +1 +1 -1  -19.6       1
298 +1 +1 +1 +1 +1 +1 -1 +1 +1  -17.2       1
330 +1 +1 +1 +1 -1 +1 +1 +1 +1  -17.2       1
338 +1 +1 -1 +1 +1 +1 +1 +1 +1  -17.2       1
340 -1 +1 +1 +1 +1 +1 +1 +1 +1  -17.2       1
342 +1 -1 +1 +1 +1 +1 +1 +1 +1  -17.2       1
346 +1 +1 +1 -1 +1 +1 +1 +1 +1  -17.2       1
362 +1 +1 +1 +1 +1 -1 +1 +1 +1  -17.2       1
426 +1 +1 +1 +1 +1 +1 +1 -1 +1  -17.2       1
85  +1 +1 +1 +1 +1 +1 +1 -1 -1  -13.2       1
149 +1 +1 +1 +1 +1 -1 +1 +1 -1  -13.2       1
173 +1 +1 -1 +1 +1 +1 +1 +1 -1  -13.2       1
213 +1 +1 +1 +1 +1 +1 -1 +1 -1  -13.2       1
42  +1 +1 +1 +1 +1 +1 -1 -1 -1  -10.8       1
146 +1 +1 -1 +1 +1 -1 +1 +1 -1  -10.8       1
293 +1 +1 +1 -1 +1 +1 -1 +1 +1  -10.8       1
299 -1 +1 +1 +1 +1 +1 -1 +1 +1  -10.8       1
325 +1 +1 +1 -1 -1 +1 +1 +1 +1  -10.8       1
329 +1 -1 +1 +1 -1 +1 +1 +1 +1  -10.8       1
337 +1 -1 -1 +1 +1 +1 +1 +1 +1  -1

In [8]:
# Ising model should look like
model = dimod.BinaryQuadraticModel.from_ising(linear,quadratic, offset =0)
model    


BinaryQuadraticModel({0: -1.2, 1: -1.2, 2: -1.2, 3: -1.2, 4: -1.2, 5: -1.2, 6: -1.2, 7: -1.2, 8: 0.0}, {(0, 1): -1.0, (0, 3): -1.0, (0, 2): -1.0, (0, 6): -1.0, (1, 2): -1.0, (1, 4): -1.0, (1, 7): -1.0, (2, 5): -1.0, (2, 8): -1.0, (3, 4): -1.0, (3, 6): -1.0, (3, 5): -1.0, (4, 5): -1.0, (4, 7): -1.0, (5, 8): -1.0, (6, 7): -1.0, (6, 8): -1.0, (7, 8): -1.0}, 0, 'SPIN')

In [9]:
#conversion to binary
model = dimod.BinaryQuadraticModel.from_ising(linear,quadratic, offset = 0.0)
Q=model.to_qubo() 
Q

({(0, 1): -4.0,
  (0, 3): -4.0,
  (0, 2): -4.0,
  (0, 6): -4.0,
  (1, 2): -4.0,
  (1, 4): -4.0,
  (1, 7): -4.0,
  (2, 5): -4.0,
  (2, 8): -4.0,
  (3, 4): -4.0,
  (3, 6): -4.0,
  (3, 5): -4.0,
  (4, 5): -4.0,
  (4, 7): -4.0,
  (5, 8): -4.0,
  (6, 7): -4.0,
  (6, 8): -4.0,
  (7, 8): -4.0,
  (0, 0): 5.6,
  (1, 1): 5.6,
  (2, 2): 5.6,
  (3, 3): 5.6,
  (4, 4): 5.6,
  (5, 5): 5.6,
  (6, 6): 5.6,
  (7, 7): 5.6,
  (8, 8): 8.0},
 -8.4)

In [10]:
type(Q[0]),type(Q[1]) #quadratic and offset

(dict, float)

In [11]:
bqm = dimod.BinaryQuadraticModel({0:0 ,1:0 ,2:0 ,3:0,4:0,5:0,6:0,7:0,8:0},Q[0],Q[1], 'BINARY')
sampleset = dimod.ExactSolver().sample(bqm)
print(sampleset)
#checking if conversion to binary is correct or not
#should replicate same sampleset energy values as Ising(SPIN)

     0  1  2  3  4  5  6  7  8 energy num_oc.
341  1  1  1  1  1  1  1  1  1  -27.6       1
170  1  1  1  1  1  1  1  1  0  -19.6       1
298  1  1  1  1  1  1  0  1  1  -17.2       1
330  1  1  1  1  0  1  1  1  1  -17.2       1
338  1  1  0  1  1  1  1  1  1  -17.2       1
340  0  1  1  1  1  1  1  1  1  -17.2       1
342  1  0  1  1  1  1  1  1  1  -17.2       1
346  1  1  1  0  1  1  1  1  1  -17.2       1
362  1  1  1  1  1  0  1  1  1  -17.2       1
426  1  1  1  1  1  1  1  0  1  -17.2       1
85   1  1  1  1  1  1  1  0  0  -13.2       1
149  1  1  1  1  1  0  1  1  0  -13.2       1
173  1  1  0  1  1  1  1  1  0  -13.2       1
213  1  1  1  1  1  1  0  1  0  -13.2       1
42   1  1  1  1  1  1  0  0  0  -10.8       1
146  1  1  0  1  1  0  1  1  0  -10.8       1
293  1  1  1  0  1  1  0  1  1  -10.8       1
299  0  1  1  1  1  1  0  1  1  -10.8       1
325  1  1  1  0  0  1  1  1  1  -10.8       1
329  1  0  1  1  0  1  1  1  1  -10.8       1
337  1  0  0  1  1  1  1  1  1  -1

In [12]:
#matrix generation
model = dimod.BinaryQuadraticModel({0:0 ,1:0 ,2:0 ,3:0,4:0,5:0,6:0,7:0,8:0},Q[0],Q[1],dimod.BINARY)
model.to_numpy_matrix(variable_order=[0,1,2,3,4,5,6,7,8])

array([[5.6, -4.0, -4.0, -4.0, 0.0, 0.0, -4.0, 0.0, 0.0],
       [0, 5.6, -4.0, 0.0, -4.0, 0.0, 0.0, -4.0, 0.0],
       [0, 0, 5.6, 0.0, 0.0, -4.0, 0.0, 0.0, -4.0],
       [0, 0, 0, 5.6, -4.0, -4.0, -4.0, 0.0, 0.0],
       [0, 0, 0, 0, 5.6, -4.0, 0.0, -4.0, 0.0],
       [0, 0, 0, 0, 0, 5.6, 0.0, 0.0, -4.0],
       [0, 0, 0, 0, 0, 0, 5.6, -4.0, -4.0],
       [0, 0, 0, 0, 0, 0, 0, 5.6, -4.0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8.0]], dtype=object)

In [13]:
#Single function taking B,JJ  input and giving corresponding Hamiltonian matrix: (This is only for 3X3 lattice)
def matr(B,JJ):
    Kb = 1.0
    mu = 1.0
     
    b=-1.0*mu*B  #bias
    c=-1.0*JJ  #coupler
    
    linear={0:b, 1: b, 2: b , 3: b , 4:b , 5:b,6:b ,7:b}
    quadratic={(0,1):c, (0,3):c, (0,2):c ,(0,6):c, (1,2):c, (1,4):c, (1,7):c\
          ,(2,5):c, (2,8):c, (3,4):c, (3,6):c, (3,5):c, (4,5):c, (4,7):c\
          ,(5,8):c, (6,7):c, (6,8):c, (7,8):c}
    model = dimod.BinaryQuadraticModel.from_ising(linear,quadratic, offset =0)
    Q=model.to_qubo()
    linear={0:0, 1: 0, 2: 0 , 3: 0 , 4:0, 5:0,6:0 ,7:0}
    model = dimod.BinaryQuadraticModel(linear,Q[0],Q[1],dimod.BINARY)
    matrix=model.to_numpy_matrix(variable_order=[0,1,2,3,4,5,6,7,8])
    
    
    return matrix
    
    
    
    
    

In [14]:
matr(0.5,1)   #checking whether function works or not

array([[7.0, -4.0, -4.0, -4.0, 0.0, 0.0, -4.0, 0.0, 0.0],
       [0, 7.0, -4.0, 0.0, -4.0, 0.0, 0.0, -4.0, 0.0],
       [0, 0, 7.0, 0.0, 0.0, -4.0, 0.0, 0.0, -4.0],
       [0, 0, 0, 7.0, -4.0, -4.0, -4.0, 0.0, 0.0],
       [0, 0, 0, 0, 7.0, -4.0, 0.0, -4.0, 0.0],
       [0, 0, 0, 0, 0, 7.0, 0.0, 0.0, -4.0],
       [0, 0, 0, 0, 0, 0, 7.0, -4.0, -4.0],
       [0, 0, 0, 0, 0, 0, 0, 7.0, -4.0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8.0]], dtype=object)

In [15]:
#Checking whether matrix multliplication works
import numpy as np

In [16]:
U = [1.0 for k in range(9)]
U

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

In [17]:
np.dot(matr(B,JJ),U)

array([-10.4, -6.4, -2.4000000000000004, -6.4, -2.4000000000000004,
       1.5999999999999996, -2.4000000000000004, 1.5999999999999996, 8.0],
      dtype=object)